Bkstg\FOSUserBundle\Entity\ProductionRole:
    type: entity

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
        designation:
            type: string

    manyToOne:
        production_membership:
            targetEntity: Bkstg\FOSUserBundle\Entity\ProductionMembership
            inversed_by: production_roles
