Bkstg\FOSUserBundle\Entity\ProductionMembership:
    type: entity
    repositoryClass: Bkstg\FOSUserBundle\Repository\ProductionMembershipRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        active:
            type: boolean
        roles:
            type: array
        expiry:
            type: datetime
            nullable: true
    manyToOne:
        member:
            targetEntity: Bkstg\FOSUserBundle\Entity\User
            inversedBy: memberships
        group:
            targetEntity: Bkstg\CoreBundle\Entity\Production
    oneToMany:
        production_roles:
            targetEntity: Bkstg\FOSUserBundle\Entity\ProductionRole
            mappedBy: production_membership
            cascade: [persist, remove]

