Bkstg\FOSUserBundle\Entity\Profile:
    type: entity
    repositoryClass: Bkstg\FOSUserBundle\Repository\ProfileRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        first_name:
            type: string
            nullable: true
        last_name:
            type: string
            nullable: true
        email:
            type: string
            nullable: true
        height:
            type: length
            nullable: true
        weight:
            type: mass
            nullable: true
        phone:
            type: string
            nullable: true
        facebook:
            type: string
            nullable: true
        twitter:
            type: string
            nullable: true
        slug:
            type: string
            gedmo:
                slug:
                    fields:
                        - first_name
                        - last_name

    oneToOne:
        user:
            targetEntity: Bkstg\FOSUserBundle\Entity\User
            mappedBy: profile
        membership:
            targetEntity: Bkstg\FOSUserBundle\Entity\ProductionMembership
            inversedBy: profile
        image:
            targetEntity: Bkstg\MediaBundle\Entity\Media
            cascade:
                - persist
                - remove
