Bkstg\FOSUserBundle\Entity\User:
    type: entity
    repositoryClass: Bkstg\FOSUserBundle\Repository\UserRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    oneToMany:
        memberships:
            targetEntity: Bkstg\FOSUserBundle\Entity\ProductionMembership
            mappedBy: member
            cascade:
                - remove
    oneToOne:
        profile:
            targetEntity: Bkstg\FOSUserBundle\Entity\Profile
            mappedBy: user
            cascade:
                - remove
