Bkstg\FOSUserBundle\Entity\User:
    type: entity
    repositoryClass: Bkstg\FOSUserBundle\Repository\UserRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        has_profile:
            type: boolean
        first_name:
            type: string
            nullable: true
        last_name:
            type: string
            nullable: true
        height:
            type: length
            nullable: true
        weight:
            type: mass
            nullable: true
        phone:
            type: string
            nullable: true
        facebook:
            type: string
            nullable: true
        twitter:
            type: string
            nullable: true
        slug:
            type: string
            gedmo:
                slug:
                    fields:
                        - first_name
                        - last_name

    oneToMany:
        memberships:
            targetEntity: Bkstg\FOSUserBundle\Entity\ProductionMembership
            mappedBy: member
            cascade:
                - remove
    oneToOne:
        image:
            targetEntity: Bkstg\MediaBundle\Entity\Media
            cascade:
                - persist
                - remove
