services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Bkstg\FOSUserBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'
    Bkstg\FOSUserBundle\EventListener\MembershipCreator:
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }
    Bkstg\FOSUserBundle\EventListener\MembershipDeletion:
        tags:
            - { name: doctrine.event_listener, event: preRemove, lazy: true }
