services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Bkstg\FOSUserBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests,EventListener,Spread,Resources}'

    # Controller services.
    Bkstg\FOSUserBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags:
            - { name: controller.service_arguments }

    # Doctrine event listeners.
    Bkstg\FOSUserBundle\EventListener\MembershipCreator:
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }
    Bkstg\FOSUserBundle\EventListener\MembershipDeletion:
        tags:
            - { name: doctrine.event_listener, event: preRemove, lazy: true }

    # Service aliases for autowiring.
    Bkstg\CoreBundle\User\MembershipProviderInterface: '@Bkstg\FOSUserBundle\User\MembershipProvider'
    Bkstg\CoreBundle\User\ProfileProviderInterface: '@Bkstg\FOSUserBundle\User\ProfileProvider'
    Bkstg\CoreBundle\User\UserProviderInterface: '@Bkstg\FOSUserBundle\User\UserProvider'
