services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Bkstg\FOSUserBundle\Timeline\:
        resource: '../../Timeline/*'

    # Spread services.
    Bkstg\FOSUserBundle\Timeline\Spread\:
        resource: '../../Timeline/Spread'
        public: true
        tags:
            - { name: spy_timeline.spread }

    # Doctrine event listeners.
    Bkstg\FOSUserBundle\Timeline\EventListener\MembershipTimelineListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist, lazy: true }
