<?php

namespace Bkstg\FOSUserBundle\Repository;

use Bkstg\FOSUserBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends EntityRepository
{
    public function findProfile(UserInterface $user)
    {
        $profile = null;

        // Get a query builder and build a query.
        $qb = $this->createQueryBuilder('p');
        $query = $qb
            ->join('p.user', 'u')
            ->andWhere($qb->expr()->eq('u', ':user'))
            ->setParameter('user', $user)
            ->getQuery();

        try {
            $profile = $query->getSingleResult();
        } catch (NoResultException $e) {
            // Nothing to be concerned about.
        }

        return $profile;
    }

    public function findAllEnabled()
    {
        // Get a query builder and build a query.
        $qb = $this->createQueryBuilder('p');
        $query = $qb
            ->join('p.user', 'u')
            ->andWhere($qb->expr()->eq('u.enabled', 1))
            ->getQuery();

        return $query->getResult();
    }

    public function findAllBlocked()
    {
        // Get a query builder and build a query.
        $qb = $this->createQueryBuilder('p');
        $query = $qb
            ->join('p.user', 'u')
            ->andWhere($qb->expr()->eq('u.enabled', 0))
            ->getQuery();

        return $query->getResult();
    }
}
