<?php

namespace Bkstg\FOSUserBundle\Repository;

use Bkstg\FOSUserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllActive()
    {
        return $this->findBy(['status' => User::STATUS_ACTIVE]);
    }
    public function findAllBlocked()
    {
        return $this->findBy(['status' => User::STATUS_BLOCKED]);
    }
}
