<?php

namespace Bkstg\FOSUserBundle\Repository;

use Bkstg\CoreBundle\Entity\Production;
use Bkstg\FOSUserBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getAllActiveQuery()
    {
        $qb = $this->createQueryBuilder('u');
        return $qb
            ->andWhere($qb->expr()->eq('u.enabled', ':enabled'))
            ->setParameter('enabled', true)
            ->getQuery();
    }

    public function getAllBlockedQuery()
    {
        $qb = $this->createQueryBuilder('u');
        return $qb
            ->andWhere($qb->expr()->eq('u.enabled', ':enabled'))
            ->setParameter('enabled', false)
            ->getQuery();
    }

    public function findAllActive()
    {
        return $this->getAllActiveQuery()->getResult();
    }

    public function findAllBlocked()
    {
        return $this->getAllBlockedQuery()->getResult();
    }

    public function findUsersByGroup(Production $production)
    {
        $qb = $this->createQueryBuilder('u');
        return $qb
            ->join('u.memberships', 'm')
            ->join('m.group', 'g')
            ->andWhere($qb->expr()->eq('g', ':group'))
            ->setParameter('group', $production)
            ->getQuery()
            ->getResult();
    }
}
