<?php

namespace Bkstg\FOSUserBundle\Repository;

use Bkstg\CoreBundle\Entity\Production;
use Bkstg\FOSUserBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getAllActiveQuery(bool $with_profile = false)
    {
        $qb = $this->createQueryBuilder('u');
        $qb
            ->andWhere($qb->expr()->eq('u.enabled', ':enabled'))
            ->setParameter('enabled', true)
        ;
        if ($with_profile) {
            $qb->andWhere($qb->expr()->orX(
                $qb->expr()->isNotNull('u.first_name'),
                $qb->expr()->isNotNull('u.last_name')
            ));
        }
        return $qb->getQuery();

    }

    public function getAllBlockedQuery(bool $with_profile = false)
    {
        $qb = $this->createQueryBuilder('u');
        $qb
            ->andWhere($qb->expr()->eq('u.enabled', ':enabled'))
            ->setParameter('enabled', false)
        ;
        if ($with_profile) {
            $qb->andWhere($qb->expr()->orX(
                $qb->expr()->isNotNull('u.first_name'),
                $qb->expr()->isNotNull('u.last_name')
            ));
        }
        return $qb->getQuery();
    }

    public function findAllActive(bool $with_profile = false)
    {
        return $this->getAllActiveQuery($with_profile)->getResult();
    }

    public function findAllBlocked(bool $with_profile = false)
    {
        return $this->getAllBlockedQuery($with_profile)->getResult();
    }

    public function findUsersByGroup(Production $production)
    {
        $qb = $this->createQueryBuilder('u');
        return $qb
            ->join('u.memberships', 'm')
            ->join('m.group', 'g')
            ->andWhere($qb->expr()->eq('g', ':group'))
            ->setParameter('group', $production)
            ->getQuery()
            ->getResult();
    }
}
