# Contrib routes.
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# User bundle routes.
bkstg_profile:
    resource: '@BkstgFOSUserBundle/Resources/config/routing/profile.yml'
    prefix: /directory
bkstg_production_profile:
    resource: '@BkstgFOSUserBundle/Resources/config/routing/production_profile.yml'
    prefix: /{production_slug}/directory
bkstg_user:
    resource: '@BkstgFOSUserBundle/Resources/config/routing/user_admin.yml'
    prefix: /admin/users
bkstg_membership:
    resource: '@BkstgFOSUserBundle/Resources/config/routing/membership.yml'
    prefix: /{production_slug}/settings/members
