bkstg_directory_index:
    path: /
    methods: [GET]
    defaults:
        _controller: Bkstg\FOSUserBundle\Controller\DirectoryController:indexAction
bkstg_directory_read:
    path: /{profile_slug}
    methods: [GET]
    defaults:
        _controller: Bkstg\FOSUserBundle\Controller\DirectoryController:readAction
