bkstg_directory_list:
    path: /
    defaults:
        _controller: Bkstg\FOSUserBundle\Controller\DirectoryController:indexAction
bkstg_directory_show:
    path: /{profile_slug}
    defaults:
        _controller: Bkstg\FOSUserBundle\Controller\DirectoryController:readAction
