bkstg_membership_list:
    path: /
    defaults:
        _controller: Bkstg\FOSUserBundle\Controller\ProductionMembershipController:indexAction
bkstg_membership_create:
    path: /add
    defaults:
        _controller: Bkstg\FOSUserBundle\Controller\ProductionMembershipController:createAction
bkstg_membership_edit:
    path: /{id}/edit
    defaults:
        _controller: Bkstg\FOSUserBundle\Controller\ProductionMembershipController:updateAction
bkstg_membership_delete:
    path: /{id}/delete
    defaults:
        _controller: Bkstg\FOSUserBundle\Controller\ProductionMembershipController:deleteAction
