bkstg_production_directory_list:
    path: /
    defaults:
        _controller: Bkstg\FOSUserBundle\Controller\ProductionDirectoryController:indexAction
bkstg_production_directory_show:
    path: /{profile_slug}
    defaults:
        _controller: Bkstg\FOSUserBundle\Controller\ProductionDirectoryController:readAction
