bkstg_production_profile_list:
    path: /
    defaults:
        _controller: Bkstg\FOSUserBundle\Controller\ProductionProfileController:indexAction
bkstg_production_profile_show:
    path: /{profile_slug}
    defaults:
        _controller: Bkstg\FOSUserBundle\Controller\ProductionProfileController:readAction
