bkstg_profile_list:
    path: /
    defaults:
        _controller: Bkstg\FOSUserBundle\Controller\ProfileController:indexAction
bkstg_profile_show:
    path: /{profile_slug}
    defaults:
        _controller: Bkstg\FOSUserBundle\Controller\ProfileController:readAction
bkstg_profile_edit:
    path: /{id}/edit
    defaults:
        _controller: Bkstg\FOSUserBundle\Controller\ProfileController:updateAction
