bkstg_profile_read:
    path: /
    defaults:
        _controller: Bkstg\FOSUserBundle\Controller\ProfileController:readAction
bkstg_profile_update:
    path: /edit
    defaults:
        _controller: Bkstg\FOSUserBundle\Controller\ProfileController:updateAction
